# Generated by Django 2.0 on 2020-07-19 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPais',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.AddField(
            model_name='historicalprovincia',
            name='pais',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.Pais'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parametros.Pais'),
            preserve_default=False,
        ),
    ]
