# Generated by Django 2.0 on 2020-07-20 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=200, verbose_name='Estado (*)')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalServicio',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('pago', models.BooleanField(default=False, verbose_name='Pagó (*)')),
                ('fechaRecepcion', models.DateField(blank=True, editable=False, verbose_name='Fecha de Recepcion (*)')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha de Entrega (*)')),
                ('manoDeObra', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Mano de Obra (*)')),
                ('importeFinal', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Importe Final')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipos.Equipo')),
                ('estado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicios.EstadoServicio')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical servicio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NivelUrgencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=200, verbose_name='Nivel de Urgencia (*)')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pago', models.BooleanField(default=False, verbose_name='Pagó (*)')),
                ('fechaRecepcion', models.DateField(auto_now=True, verbose_name='Fecha de Recepcion (*)')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha de Entrega (*)')),
                ('manoDeObra', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Mano de Obra (*)')),
                ('importeFinal', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Importe Final')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipos.Equipo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.EstadoServicio')),
                ('nivelUrgencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.NivelUrgencia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo de Servicio (*)')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.TipoServicio'),
        ),
        migrations.AddField(
            model_name='historicalservicio',
            name='nivelUrgencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicios.NivelUrgencia'),
        ),
        migrations.AddField(
            model_name='historicalservicio',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicios.TipoServicio'),
        ),
    ]
