# Generated by Django 2.0 on 2020-08-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=200, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='telefono',
            field=models.CharField(max_length=200, verbose_name='Telefono'),
        ),
    ]
